<template>
  <!-- Section: Icon Boxes -->
  <div>
  <section class="section section-icons indigo  center">
    <div class="container">
      <div class="row">
        <div class="col s12 m8">
          <div class="card-panel z-depth-5">
            <h4 class="left-align">Computational Finance Research</h4>

            <h6 class="left-align">
            <strong> Automation and Machine Learning in the Capital Markets </strong>
            </h6>
            <p class="left-align">
               by Oscar H. Criner 
            </p>
            <p class="left-align">
              Are the results of using mathematics and physics in economics and finance 
              "too good to be true"? The physicist Eugene Wigner published a paper in 1960 entitled 
              "The unreasonable effectiveness of mathematics in the natural sciences." He had observed 
              that "mathematical concepts turn up in entirely unexpected connections. Moreover, they 
              often permit an unexpectedly close and accurate description of the phenomena in these
              connections." This document is a story, a memoir, of my discovery of several of those 
              unreasonably effective relationships of mathematics in the course of my research in computational finance.
            </p>
            <p class="left-align">
            <strong> Time Series in the Flesh </strong>
            </p>
            <p class="left-align">
            In 1962, my first professional position in the computing industry was reducing data from 
            the transducers on the accelerometers in a missile test program. These data presented 
            in large graphs of measurements by the millisecond, drawn as oscillograph records on 
            cylindrical rolls a foot high, a foot in diameter, and hundreds of feet long. Analysts 
            would roll these one foot wide cylinders of paper, as if bowling the roll, down a very 
            long hallway in the plant and walk along the stream of paper to identifying (eyeballing) 
            anomalies in the trace and estimating the measurements using a Gerber scale. There were 
            no computer programs to do this function at that time. There was an IBM 709 in this plant, 
            and an IBM 7090 was coming. The IBM 709 was a vacuum tube machine, and the IBM 7090 
            was a transistor based machine. 
            </p>
            <p class="left-align">
            In college, I was interested in the graphs and tables of the Dow Jones Average and other 
            financial instruments in the financial newspapers. They seemed interesting because these large 
            tables of numbers dominated the business pages in the newspapers every day. To figure out what they 
            meant, I had to make the time-series of what was of interest by hand. I began to use a computer and 
            punched cards for my data after I obtained access to a machine. However, it was manual for a long 
            time. Mathematics majors in college usually study differential equations. My real interest was logic, 
            foundations of mathematics and the philosophy of science; but industry did not pay for philosophers, 
            so differential equations, the calculus of variations, and computer programming ensured employment.
            </p>
            <p class="left-align">
          	The study of dynamical systems usually results in finding the solutions of time-dependent 
            ordinary differential equations, which are functions of time. These solutions become time 
            series when the solutions are numerically evaluated. The difficulty in finance is that there do not 
            exist equation of fundamental principles as there are in physics. The time series are all emperical 
            and come from the measurements in the markets.
          </p>
            <p class="left-align">
            I was looking for the connections between the two kinds of time series, one generated by 
            the measurements of the accelerometer on a rocket and the other resulting from the 
            trading activity of people in a market. I was trying to determine if there was any 
            connection between the mathematics or physical principles underlying both time series, 
            which looked very similar but were generated by vastly different processes. Time series 
            may occur as a result of many kinds of procedures. Time series are everywhere. Time 
            series are so important and pervasive in modern society that the Federal Reserve Bank of 
            St. Louis maintains a collection of more than "500,000 US and international time series 
            from 87 sources" in its database, FRED, the Federal Reserve Economic Database.  

            The vast number of time-series in FRED has to be analyzed to determine precisely the manner 
            in which they relate to the world economy, however, the number of people capable of a
            nalyzing them is much smaller. Software tools are needed to explain some of these objects. 
            Many everyday things can have a time series perspective or point of view. Music is a time 
            series; movies are time series, telephone calls are time series.  Automation will be 
            implemented in all sorts of applications that require the analyses of complex time series.  
            Autonomous vehicles will have many time series varying in time, space, and architecture in 
            dynamic short range ad-hoc networks. 
            </p>
            <p class="left-align">
            Financial time series of electronically traded funds (ETFs) are growing fast. There are more 
            than 1600 ETFs today and more being created every day. Just imagine that if we have 8000 stocks 
            arranged in fund portfolios of 100 issues each, then there is an astronomical number of possible 
            portfolios. Attempting to analyze this number of possible collections of equities would overwhelm 
            all the existing human fund managers and their methods of analysis. An automated tool does not 
            exist that can find the optimal portfolios from such a collection. Automation is needed to analyze 
            such a large number of portfolios.  Go to Excel and choose the “Formulas” tab, then choose 
            the “Math & Trig” tab, then choose the “COMBIN” function and enter 8000 as the number 
            and 100 as the number that is chosen, then the result is 1.1746x10exp(232) portfolios. This is
            an enormous number, 11746 with 228 zeros behind it. 
            </p>
            <p class="left-align">
            In financial markets, the conventional wisdom is that to make a profit one must “buy low and 
            sell high.” At least, that what the old traders told me when I first began studying the markets 
            back in the 1960s. The catch is that they never said how you do it. They probably did not know, 
            at least in the terms that I will discuss in this little essay. Trading futures and ETFs is 
            essentially a zero-sum game. It takes two players to engage in a zero-sum game where whatever 
            one player wins; the other must lose. Most popular zero-sum games are two-person games; beginning 
            with the children’s game Tic-Tac-Toe, on to checkers, and to chess, which is an exceptionally 
            complicated two-person zero-sum game, because of the architecture of the game, where the number 
            of possible moves together with the sequence of those moves is astronomical. IBM is building an 
            industry from its apparent solution of the chess problem with Watson, it super sophisticated program 
            to play chess with a computer. That it is possible to play these games with computers has been known 
            to computer scientists and mathematicians for a very long time. IBM had the resources and the 
            political will to build the machine and software do it.
            </p>
            <p class="left-align">
            Trading ETFs and futures is an enormous zero-sum game that has evolved a business 
            infrastructure that facilitates large-scale worldwide fully electronic operations. 
            When viewed this way, there are two player populations called “the Bulls” and “the Bears” 
            in the traditional view of the financial markets. The Bulls believe that the trading 
            instrument is going up in value and the Bears believe that it is going down. Many people 
            believe that the analysis of financial charts provides the information as to whether the 
            particular market is going up or down. Financial charts are old technology but with 
            questionable success, historically. In this twenty-first century, everything will be 
            automated, and many companies are pursuing the competitive trading advantage with 
            computing algorithms. Driverless cars will soon be a reality as will pilotless commercial 
            airplanes. Smart houses with smart appliances and all manner of intelligent products 
            will be available on the internet of things, and automation becomes an integral part of 
            everyday life. If you can trust your life to an autonomous airplane, then you can surely 
            trust your financial life to an autonomous financial manager that can determine “up” from 
            “down” like an autonomous airplane and with astounding results. The days of struggling 
            with vague chart pattern interpretations to predict market directions and trading are gone 
            forever.
            </p>  
            <p class="left-align">
            In the era that promotes artificial intelligence, machine learning, amd big data that is 
            available to everyone, it should be no surprise that such autonomous financial analytics is 
            possible and that it is more successful than most people can imagine. Even professionals in the
            investment and trading industry are unaware of the potential. The infrastructure of financial 
            markets has coalesced into a few highly automated broker companies that operate the electronic 
            financial exchanges and the direct market access system. The trading public has a right to have 
            a higher technology in information analysis that is much more effective in facilitating decision 
            making in these markets. We present here results of scientific and computational modeling of the 
            markets, and you can judge for yourselves the effectiveness of the analytics. First, however, one 
            must understand the methodology.
            </p>
            <p class="left-align">
            In the most critical aspects of human endeavor today, we find computers and automation are pervasive. 
            We see pilots in airplanes bored because of automation that they find themselves doing nothing on 
            long flights. Remarkably, air travel is the safest form of transportation. Automation in the 
            transportation industry will become widespread and pervasive as driverless cars, trucks, and the 
            physical infrastructure becomes accepted by the community. I can envisage one day being able to get 
            in my vehicle and telling it to “take me home,” and it does so safely and quickly. We trust our 
            physical lives to mission-critical computing systems everyday. There are certainly many instances of 
            traffic accidents because someone did not obey the rules, but relatively few are the result of the 
            automated systems failing. We are aware of the recent airline, automobile, and train accidents that 
            are related to the implementation of process improvement and automation. Systems should be designed 
            to prevent users from aborting the operational rules.
            
            In many cases, user-barriers can prevent users from violating rules or enforcing punishment 
            for breaking the law. In my city, it took an “act of the city council” to put traffic restriction 
            barriers at some railroad crossings to prevent impatient drivers from going around simple railroad 
            crossing traffic arms into an accident. But the voters in this city also stopped the use of red 
            light cameras that photographed drivers breaking traffic laws. In our financial and economic systems, 
            it will take an “act of Congress” to put in place the barriers that prevent “accidents” in our 
            ill-designed financial systems. In another artivle "Revisiting the Financial Crisis of 2007" a 
            different view of financial analytics of the  crisis that created the Great Recession is given. 
            It shows that with a little scientific and engineering  perspective applied in finance and economics, 
            one could have identified the “accident on its way to a happening" and the Great recession could have
            been avoided,
           </p>
            <p class="left-align">
            <h6 class="left-align">Fundamentals of dynamical systems</h6
            </p>
            <p class="left-align">
	          What we desire is to have a logical system, like Newtonian mechanics, that if applied to economic and 
            financial systems and behaviors will provide the ability to predict or explain the observed phenomena. 
            For space travel, the fundamental physics and mechanics is well-known for centuries, but the engineering 
            to accomplish space flight did not exist until the last half of the twentieth century. Newtonian dynamics 
            is not an easily realizable theory. Many problems in mechanics have intractable mathematics that does not 
            yield neat “closed form solutions.” Many of these problems were not solved until the advent of the 
            digital computer. Even more difficult problems than space travel exist in modern automation technology 
            being employed to modernize the technological infrastructure. The need for computation of fire control tables 
            for guns in World War II (WW2) lead to the development of the digital computer and the internal instruction 
            machine was developed to solve fluid flow problems in hydrogen bomb development. However, the air-to-ground 
            missile problem did not yield until the development and implementation of global positioning systems, 
            which is a systems engineering triumph combining several complex systems of machines and human beings working 
            together.
            </p>
            <p class="left-align">
            I like to use the transportation analogy to explain these ideas because most people have experienced and can 
            relate to the issues of transportation. For example, major vibration issues occur in all transportation modalities.  
            When I was a kid, my father told me that the cruising speed of an automobile is that speed where all of the 
            vibrations in the car were least and had smoothed out. My father always bought used cars, so we spent lots of 
            time listening, feeling, and identifying the causes of the vibrations in these cars. The most common vibration 
            occurs when the tires are unbalanced. Many other vibrations arise because of “wear and tear.” Strong vibrations 
            in any vehicle are usually the sign that something is not right. Applications of the theory of dynamical systems 
            and control to economics and finance has been developing for some time. However, there are no mathematical 
            models of the type found in physical science and, hence, no dynamical systems theory is available. Instead, 
            the data that the economic system produces must be used to derive a systems identification and these data are 
            usually in the form of time series. 
            </p>
            <p class="left-align">
            The problem of constructing a description of a system from the measurements of the output of that system is 
            called an “inverse problem.” Contrast this with a “direct problem” that is defined with well-accepted scientific 
            theories like physics, chemistry, or biology. Even in these sciences, there are difficult problems that are 
            attacked as inverse problems, but with the knowledge of the quantitative sciences. To accomplish inverse 
            system identification, one should have information on the vibratory behavior of the dynamical systems. Fig. 2 
            shows the graph of the free vibrations of a simple harmonic oscillator, e.g., a mass on a spring with no 
            driving force. If the mass is displaced and released the resulting motion is described by the well-known 
            sine function, and this is called simple harmonic motion. In Fig. 2 the value of the function is measured on 
            the vertical axis and time is on the horizontal axis so that each point on the graph is a pair -- a time and 
            a value, which is called an ordered pair (time, price). It could be the displacement of the mass or some 
            other parameter vibrating and still described by a time series.
            </p>
            <p class="left-align">
            <img src="../../assets/images/Simple sine wave SHM.jpg" class="imgsmall center-align responsive">
            </p>
            <p class="left-align">
            Hence, the above graph is a set of ordered pairs. In fact, a formal mathematical definition of a function is 
            a set of ordered pairs, where no two pairs have the same first element. For a given time series this means 
            that no two events occur at the same time. 
            

            </p>
            <p class="left-align">
            <img src="../../assets/images/Historical Bubble S and P.gif" class="imglarge responsive">
            <h6 class="left-align">Optimal Control Strategies for Portfolios of Managed Futures</h6>
            <p class="left-align">
               by Oscar H. Criner 
            </p>
            <p class="left-align">
               <strong> Abstract </strong>
            </p>
            <p class="left-align">
              The problem: Given only historical trading price-time data for the 
              formally traded financial instrument of interest (portfolio), what 
              trading decisions should be made at the current point in time so 
              that the chosen performance measure of the portfolio is maximized? 
              Advancing computing technology has encouraged development of an 
              extremely large number of computational tools to solve this problem. 
              Most of these tools employ pattern recognition, moving averages, or 
              neural nets. Few, if any, attempts have been made to cast the 
              problem into a single consistent theoretical framework. We use the 
              theory of optimal control of differential equations as the framework 
              and seek an inverse solution for the controller. Given a price-time 
              trajectory]\\he policies that optimize performance over that 
              trajectory]\\that the behavior continues into the future for 
              some time,]\\l control strategies are the result. This paper 
              reports on]\\of research that succeeded in that effort.
            </p>
            <p class="left-align">
               The essence of a control theoretic approach is to: 1) develop a 
               measure of profitability of the trading portfolio, 2) 
               computationally model the trading process operating on the 
               price-time histories, 3) calculate estimates of the price-time 
               histories using functions with well-known mathematical 
               characteristics, 4) calculate, using the calculated estimates, 
               derived functions of the price-time histories about which control 
               variables are known and about which there is .a priori knowledge, 
               5) simulate, using the derived functions, the trading policies and 
               seek the values of the control variables that maximize the 
               portfolio’s trading performance over the life of the trading 
               instruments. A realizable optimal control strategy is a direct 
               extrapolation of the optimal simulation of trading into the future, 
               day by day.
            </p>
            <p class="left-align">
              <i>
                Keywords: managed futures, quantitative analysis, trading 
                systems, trading simulation, dynamic systems, estimation and 
                control. 
              </i>
            </p>
            <p class="left-align">
              <img src="../../assets/images/CF2004.jpg">
            </p>
            <p class="left-align">
              <i>
                Computational Finance and Its Applications 
              </i>
              Edited by: Wessex Institute of Technology, UK ISBN: 1-85312-709-4 Published: 2004,  WIT Press, Pages: 320pp Hardback 
            </p>
            <p>



            </p>
            <h6 class="left-align">The Great Recession of 2007--2009 Revisited 2018</h6>
            <p class="left-align">
               by Oscar H. Criner 
            </p>
            <p class="left-align">
               <strong> Abstract </strong>
            </p>
            <p class="left-align">
            Markets processes may be more complex than processes in space or defense programs, 
            and automation so that it is reasonable that many traders fail and go bankrupt without 
            the benefit of modern computational science. Indeed, there is a great deal of failure 
            in the financial markets, as we have seen in recent years. However, in several high profile 
            instances the “best and the brightest” are humbled by the marketplace, e.g., Long Term 
            Capital Management, Bearings Bank, Enron, Lehman Brothers, Bear Sterns, to name a few. 
            In physics, we may be able to measure verify small, simple, slow-moving physical phenomena, 
            i.e., simple harmonic motion, projectile motion, central force fields, and the like. 
            The theories fall apart when the complexity increases, i.e., when we add lots of vibrating 
            bodies, move very fast, or consider many particles.  The science that we know and that has 
            become a part of our belief structure is insufficient for many of the problems that we want 
            to solve today.  It fails most severely when we consider social phenomena, and markets 
            are a complex combination of the social and the physical aspects. 

            </P>  

          </div> !end of card
        </div>
      </div>
    </div>
  </section>
  </div>
</template>

<style scoped>
mark{
    background-color: white;
}
.imglarge{
  width: 100%;
}
@media screen and (max-width: 900px){
  .imglarge{
  width: 100%;
  height: auto;
  }
}
</style>
